general {
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = screenshot
    color = rgba(18, 18, 18, 1.0)
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor =
    size = 280, 48
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.2
    outer_color = rgb(230, 142, 13)
    inner_color = rgb(26, 26, 26)
    font_color = rgb(190, 190, 190)
    fade_on_empty = true
    placeholder_text = <i>password...</i>
    hide_input = false
    rounding = 8
    check_color = rgb(255, 193, 7)
    fail_color = rgb(211, 95, 95)
    fail_text = <i>wrong password</i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<b>$(date +"%H:%M")</b>"
    color = rgba(190, 190, 190, 1.0)
    outline_thickness = 2
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}
