general {
    lock_cmd = hyprlock
}


# lock after 10 mins regardless
listener {
    timeout = 600
    on-timeout = hyprlock
}

# only suspend on battery
listener {
    timeout = 1500
    on-timeout = bash -c 'if [ "$(cat /sys/class/power_supply/ADP0/online)" = "0" ]; then systemctl suspend; fi'
}
